name: hani_booki
description: "호호하니&호호부키"
publish_to: 'none'
# 현재 버전
version: 1.0.16+23
# 다음 버전 1.0.17+24

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.4.0
  intl: ^0.20.1
  get: ^4.6.6
  dio: ^5.7.0
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  crypto: ^3.0.6
  encrypt: ^5.0.3
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.4
  package_info_plus: ^8.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  webview_flutter: ^4.10.0
  carousel_slider: ^5.0.0
  flip_card: ^0.7.0
  scratcher: ^2.5.0
  collection: ^1.19.0
  diff_image2: ^1.2.1
  fl_chart: ^0.70.2
  marquee: ^2.3.0
  chat_bubbles: ^1.7.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1
  path_drawing: ^1.0.1
  flutter_launcher_icons: ^0.14.3
  just_audio: ^0.9.46
  lottie: ^3.3.1
  vimeo_video_player: ^1.0.1
  flutter_inappwebview: ^6.1.5
  flutter_volume_controller: ^1.3.3
  dotted_border: ^2.1.0
  flutter_native_splash: ^2.1.8
  shared_preferences: ^2.5.2
  flutter_radar_chart: ^0.2.1
  badges: ^3.1.2
  flutter_easyloading: ^3.0.5
  connectivity_plus: ^6.1.3
  app_version_update: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/launcher.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - .env

    - assets/images/
    - assets/images/icons/
    - assets/images/kidok/
    - assets/images/hani/
    - assets/images/booki/
    - assets/images/records/
    - assets/images/temp/

    - assets/lottie/

    - assets/audio/
    - assets/audio/effect/
    - assets/audio/bgm/

    - assets/text/


  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf

    - family: Cookie
      fonts:
        - asset: assets/fonts/CookieRun.ttf

    - family: BMJUA
      fonts:
        - asset: assets/fonts/BMJUA.ttf
